# Website settings
title: "uCode EINA | 10, 11 y 12 de marzo | EINA, Zaragoza"
description: "Hackathon uCode 10, 11 y 12 de marzo en EINA (Escuela de Ingeniería y Arquitectura), Zaragoza"
keywords: "uCode,hack,hacker,hackathon,hacking,EINA,Zaragoza"
baseurl: "/"
url: "http://www.ucode.es"
logo_small: "static/img/logo/ucode_abr.png"
logo: "static/img/logo/ucode.png"

# author
author:
  name: 'Marcos Canales Mayo'
  first_name: 'Marcos'
  last_name: 'Canales Mayo'
  email: 'soporte@ucode.es'
  facebook_username: ''
  github_username: 'MarcosCM'
  head_img: 'static/img/organizers/Marcos.jpg'
  
about:
  email: 'soporte@ucode.es'

# sections
sections:
  - id: 'about'
    i18n: 'nav.about'
    name: 'Qué es'
    tpl: 'about.html'
    css: ''

  - id: 'faq'
    i18n: 'nav.faq'
    name: 'F.A.Q.'
    tpl: 'faq.html'
    css: ''

  - id: 'sponsors'
    i18n: 'nav.sponsors'
    name: 'Patrocinadores'
    tpl: 'sponsors.html'
    css: ''

#  - id: 'timeline'
#    i18n: 'nav.timeline'
#    name: 'Horario'
#    tpl: 'timeline.html'
#    css: 'timeline'

  - id: 'collaborators'
    i18n: 'nav.collaborators'
    name: 'Colaboradores'
    tpl: 'collaborators.html'
    css: ''

  - id: 'organizers'
    i18n: 'nav.organizers'
    name: 'Organizadores'
    tpl: 'organizers.html'
    css: ''

#  - id: 'blog'
#    i18n: 'nav.blog'
#    name: 'Blog'
#    tpl: 'blog.html'
#    css: 'testimonials navy-section'

  - id: 'where'
    i18n: 'nav.where'
    name: 'Dónde'
    tpl: 'where.html'
    css: ''

# localization
languages:
  - locale: 'es'
    flag: 'static/img/flags/Spain.png'

# blog img path
img_path: 'http://www.ucode.es/static/img/blog'

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

google:
  analytics:
    id: 'UA-87705893-1'

eventbrite: 'https://www.eventbrite.com/e/registro-ucode-2016-w-29071122510'