# Website settings
title: "uCode 2018 | 9, 10 y 11 de marzo | EINA, Zaragoza"
logo_title: "uCode"
description: "Hackathon uCode 9, 10 y 11 de marzo en la Escuela de Ingeniería y Arquitectura, Zaragoza"
keywords: "uCode,hack,hacker,hackathon,hacking,EINA,Zaragoza"
baseurl: "/"
url: "http://www.ucode.es"
logo_small: "static/img/logo/ucode_abr.png"
logo: "static/img/logo/ucode.png"

# author
author:
  name: 'Marcos Canales Mayo'
  first_name: 'Marcos'
  last_name: 'Canales Mayo'
  email: 'soporte@ucode.es'
  facebook_username: ''
  github_username: 'MarcosCM'
  head_img: 'static/img/organizers/Marcos.jpg'
  
about:
  email: 'soporte@ucode.es'

# sections
sections:
  - id: 'about'
    i18n: 'nav.about'
    name: 'Qué es'
    tpl: 'about.html'
    css: ''

  - id: 'signup'
    i18n: 'nav.signup'
    name: 'Inscripción'
    tpl: 'signup.html'
    css: ''

  - id: 'faq'
    i18n: 'nav.faq'
    name: 'F.A.Q.'
    tpl: 'faq.html'
    css: ''

  - id: 'challenges'
    i18n: 'nav.challenges'
    name: 'Retos'
    tpl: 'challenges.html'
    css: ''

  # - id: 'tournaments'
  #   i18n: 'nav.tournaments'
  #   name: 'Torneos'
  #   tpl: 'tournaments.html'
  #   css: ''

  - id: 'timeline'
    i18n: 'nav.timeline'
    name: 'Horario'
    tpl: 'timeline.html'
    css: 'timeline'

  - id: 'organizers'
    i18n: 'nav.organizers'
    name: 'Organizadores'
    tpl: 'organizers.html'
    css: ''

  - id: 'where'
    i18n: 'nav.where'
    name: 'Dónde'
    tpl: 'where.html'
    css: ''

# localization
languages:
  - locale: 'es'
    flag: 'static/img/flags/Spain.png'

# blog img path
img_path: 'http://www.ucode.es/static/img/blog'

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

google:
  analytics:
    id: 'UA-113559866-1'

last_edition: 'http://2017.ucode.es'