# Website settings
title: "uCode 2018 | EINA, Zaragoza"
logo_title: "uCode"
description: "Hackathon uCode EINA en la Escuela de Ingeniería y Arquitectura, Zaragoza"
keywords: "uCode,hack,hacker,hackathon,hacking,EINA,Zaragoza,adidas"
baseurl: "/"
url: "http://www.ucode.es"
logo_small: "static/img/logo/ucode_abr.png"
logo: "static/img/logo/ucode.png"

# author
author:
  name: 'Marcos Canales Mayo'
  first_name: 'Marcos'
  last_name: 'Canales Mayo'
  email: 'soporte@ucode.es'
  facebook_username: ''
  github_username: 'MarcosCM'
  head_img: 'static/img/organizers/Marcos.jpg'

about:
  email: 'soporte@ucode.es'

# sections
sections:

# localization
languages:
  - locale: 'es'
    flag: 'static/img/flags/Spain.png'

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

google:
  analytics:
    id: 'UA-87705893-1'

previous: 'http://2017.ucode.es'
